base_link: 'simple_arm_base'
gripper:
#The end effector name for grasping
  end_effector_name: 'gripper'
  # Gripper joints
  joints: ['simple_gripper_robotiq_85_left_knuckle_joint', 'simple_gripper_robotiq_85_right_knuckle_joint']
  #Posture of grippers before grasping
  pregrasp_posture: [0.048, 0.048]
  pregrasp_time_from_start: 4.0
  grasp_posture: [0.016, 0.016]
  grasp_time_from_start: 4.0
  postplace_time_from_start: 4.0
  # Desired pose from end effector to grasp [x, y, z] + [R, P, Y]
  grasp_pose_to_eef: [-0.19, 0.21, 0.98]
  grasp_pose_to_eef_rotation: [0.0, 0.0, 0.0]
  end_effector_parent_link: 'simple_gripper_robotiq_85_base_link'


#-0.19, 0.21, 1.1
